begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_temp;
select no_plan();

select ok((select relrowsecurity from pg_class where oid='public.time_punches'::regclass),'Punches have RLS enabled');
select ok((select relrowsecurity from pg_class where oid='private.facial_profiles'::regclass),'Facial profiles have RLS enabled');
select ok((select relrowsecurity from pg_class where oid='private.clock_anchors'::regclass),'Clock anchors have RLS enabled');
select ok(not has_table_privilege('anon','public.time_punches','SELECT'),'Anonymous clients cannot read punches');
select ok(not has_table_privilege('authenticated','public.time_punches','INSERT'),'Authenticated clients cannot insert punches directly');
select ok(not has_table_privilege('authenticated','private.facial_profiles','SELECT'),'Authenticated clients cannot read facial profile metadata directly');
select ok(not has_table_privilege('authenticated','private.clock_anchors','SELECT'),'Authenticated clients cannot read clock anchors directly');
select ok(not has_function_privilege('anon','public.ingest_punch(jsonb)','EXECUTE'),'Anonymous clients cannot ingest punches');
select ok(has_function_privilege('authenticated','public.ingest_punch(jsonb)','EXECUTE'),'Authenticated terminals may invoke punch ingestion');
select ok(not has_function_privilege('authenticated','public.consume_terminal_pairing(text,uuid)','EXECUTE'),'Authenticated clients cannot consume pairing codes for arbitrary users');
select ok(has_function_privilege('service_role','public.consume_terminal_pairing(text,uuid)','EXECUTE'),'Provisioning service may consume pairing codes');
select ok((select relrowsecurity from pg_class where oid='public.work_days'::regclass),'Work days have RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.attendance_calculations'::regclass),'Attendance calculations have RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.attendance_occurrences'::regclass),'Attendance occurrences have RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.bank_hours'::regclass),'Bank hours have RLS enabled');
select ok(not has_table_privilege('authenticated','public.attendance_calculations','INSERT'),'Clients cannot forge attendance calculations');
select ok(not has_table_privilege('authenticated','public.bank_hours','INSERT'),'Clients cannot forge bank-hour entries');
select ok((select relrowsecurity from pg_class where oid='private.attendance_recalculation_queue'::regclass),'Recalculation queue has RLS enabled');
select ok(not has_table_privilege('authenticated','private.attendance_recalculation_queue','SELECT'),'Clients cannot inspect the recalculation queue');
select ok(not has_function_privilege('authenticated','public.claim_attendance_recalculation(integer)','EXECUTE'),'Authenticated clients cannot lease recalculation jobs');
select ok(has_function_privilege('service_role','public.claim_attendance_recalculation(integer)','EXECUTE'),'Only the backend service can lease recalculation jobs');
select ok(has_table_privilege('service_role','public.time_punches','SELECT'),'Attendance worker may read accepted punches');
select ok(has_function_privilege('service_role','public.record_attendance_calculation(uuid,uuid,uuid,timestamptz,timestamptz,date,text,jsonb,text)','EXECUTE'),'Attendance worker may publish versioned calculations');
select ok(not has_table_privilege('authenticated','public.schedule_segments','INSERT'),'Worker grants do not expand authenticated client writes');
select ok((select relrowsecurity from pg_class where oid='public.punch_adjustments'::regclass),'Punch adjustments have RLS enabled');
select ok(not has_table_privilege('authenticated','public.punch_adjustments','INSERT'),'Clients cannot insert punch adjustments directly');
select ok(has_function_privilege('authenticated','public.create_punch_adjustment(uuid,uuid,timestamptz,text)','EXECUTE'),'Managers may request an audited punch correction');
select ok(has_table_privilege('service_role','public.punch_adjustments','SELECT'),'Attendance worker may read current punch corrections');
select ok((select relrowsecurity from pg_class where oid='public.employee_schedule_plans'::regclass),'Daily schedule plans have RLS enabled');
select ok(not has_table_privilege('authenticated','public.employee_schedule_plans','INSERT'),'Clients cannot write daily plans directly');
select ok(has_function_privilege('authenticated','public.set_employee_schedule_plan(uuid,uuid,date,uuid,integer)','EXECUTE'),'Managers may set a daily schedule plan through the guarded RPC');
select ok(not has_function_privilege('anon','public.set_employee_schedule_plan(uuid,uuid,date,uuid,integer)','EXECUTE'),'Anonymous clients cannot set daily schedule plans');
select ok(not has_function_privilege('authenticated','private.assert_employee_schedule_plan_editable(uuid,uuid,date)','EXECUTE'),'Clients cannot invoke daily-plan validation directly');

select * from finish();
rollback;
